# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mvp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.connect = QtWidgets.QPushButton(self.centralwidget)
        self.connect.setGeometry(QtCore.QRect(20, 10, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(14)
        self.connect.setFont(font)
        self.connect.setStyleSheet("QPushButton {\n"
"    background-color: red;\n"
"    color: white;\n"
"    border: 2px solid black;\n"
"    border-radius: 50px; \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: green;\n"
"}\n"
"")
        self.connect.setObjectName("connect")
        self.connect.clicked.connect(self.change_button_color)
        
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 150, 751, 391))
        font = QtGui.QFont()
        font.setFamily("72 Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        
        self.send = QtWidgets.QPushButton(self.groupBox)
        self.send.setGeometry(QtCore.QRect(0, 70, 191, 71))
        self.send.setObjectName("send")
        
        self.send_line_edit = QtWidgets.QLineEdit(self.groupBox)
        self.send_line_edit.setGeometry(QtCore.QRect(0, 160, 341, 31))
        self.send_line_edit.setObjectName("send_line_edit")
        
        self.recv_text_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.recv_text_edit.setGeometry(QtCore.QRect(420, 60, 361, 481))
        self.recv_text_edit.setObjectName("recv_text_edit")
        
        self.recieve_label = QtWidgets.QLabel(self.centralwidget)
        self.recieve_label.setGeometry(QtCore.QRect(420, 20, 91, 31))
        self.recieve_label.setObjectName("recieve_label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connect.setText(_translate("MainWindow", "Connect"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.send.setText(_translate("MainWindow", "Send"))
        self.recieve_label.setText(_translate("MainWindow", "Recieve"))
    
    def change_button_color(self):
        # 현재 버튼의 스타일을 확인하여 색상 변경
        current_style = self.connect.styleSheet()
        
        if "red" in current_style:
            # 현재 빨간색이라면 녹색으로 변경
            self.connect.setStyleSheet("QPushButton {\n"
                                       "    background-color: green;\n"
                                       "    color: white;\n"
                                       "    border: 2px solid black;\n"
                                       "    border-radius: 50px;\n"
                                       "}\n")
        else:
            # 현재 녹색이라면 빨간색으로 변경
            self.connect.setStyleSheet("QPushButton {\n"
                                       "    background-color: red;\n"
                                       "    color: white;\n"
                                       "    border: 2px solid black;\n"
                                       "    border-radius: 50px;\n"
                                       "}\n")
    



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
