# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 707)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(0, 0, 801, 521))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("C:/Users/uig94157/Downloads/이미지.png"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.photo1 = QtWidgets.QPushButton(self.centralwidget)
        self.photo1.setGeometry(QtCore.QRect(10, 530, 331, 71))
        self.photo1.setObjectName("photo1")
        self.photo2 = QtWidgets.QPushButton(self.centralwidget)
        self.photo2.setGeometry(QtCore.QRect(540, 520, 251, 81))
        self.photo2.setObjectName("photo2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.photo1.clicked.connect(self.show_photo1)
        self.photo2.clicked.connect(self.show_photo2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.photo1.setText(_translate("MainWindow", "photo1"))
        self.photo2.setText(_translate("MainWindow", "photo2"))

    def show_photo1(self):
        self.photo.setPixmap(QtGui.QPixmap("C:/Users/uig94157/Downloads/이미지.png"))

    def show_photo2(self):
        self.photo.setPixmap(QtGui.QPixmap("C:/Users/uig94157/Downloads/1710215817406.jpg"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
